version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: shellkitty_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: admin
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: bankssimulator
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: